### ISSUE TITLE
use Pods :-)

### ISSUE THREAD

**Issue by BransonGitomeh** [mize85/how-to-sane-simple#1]

**Comment by mize85** [comment]
done 3e6968e61c8a70f7502d933a64e924ca2d324e65. or any other suggestions?

**Comment by BransonGitomeh** [comment]
Get the models out of the pods

> since they are not going to be referenced specifically by that pod but rather   more of a general files as compared to route and template...models don't belong to pods [here is an issue on ember-cli repo, i think it will be considered or something like that :-)](https://github.com/ember-cli/ember-resolver/issues/28)
